sudo: false
dist: trusty
language: php

services:
  - mysql
  - postgresql

php:
  - 5.6
  - 7.0
  - 7.1

addons:
  apt:
    packages:
    - libxml2-utils

env:
  global:
    - APP_NAME=polls
  matrix:
    - DB=mysql;CLOUD=nextcloud;CORE_BRANCH=stable12
    - DB=sqlite;CLOUD=nextcloud;CORE_BRANCH=stable12
    - DB=pgsql;CLOUD=nextcloud;CORE_BRANCH=stable12
    - DB=mysql;CLOUD=owncloud;CORE_BRANCH=stable10

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  # Install NC / oC and app
  - if [ '$CLOUD' = 'nextcloud' ]; then wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh; fi
  - if [ '$CLOUD' = 'owncloud' ]; then wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh; fi
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - if [ '$CLOUD' = 'nextcloud' ]; then cd ../server; fi
  - if [ '$CLOUD' = 'owncloud' ]; then cd ../core; fi
  - ./occ app:enable $APP_NAME

before_script:
  - cd apps/$APP_NAME

script:
  # Check info.xml schema validity
  - wget https://apps.nextcloud.com/schema/apps/info.xsd
  - xmllint appinfo/info.xml --schema info.xsd --noout
  - rm info.xsd
  # Check PHP syntax errors
  - find . -name \*.php -exec php -l "{}" \;
  # Execute tests
  - make test

after_failure:
  - cat ../../data/${CLOUD}.log
