# SPDX-FileCopyrightText: 2020 Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
name: Lint

on:
  pull_request:
  push:
    branches:
      - master-*
      - next
      - stable*

jobs:
  php-cs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3']

    name: PHP-CS

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup composer and PHP
      uses: ./.github/actions/setup-composer
      with:
        php-version: ${{ matrix.php-versions }}
        php-tools: composer

    - name: Run coding standards check
      run: composer run cs:check

  eslint:
    runs-on: ubuntu-latest

    name: ESLint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Run eslint
        run: npm run lint

  stylelint:
    runs-on: ubuntu-latest

    name: Stylelint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Run stylelint
        run: npm run stylelint

