name: Lint

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  php-cs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']

    name: PHP ${{ matrix.php-versions }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup composer and PHP
      uses: ./.github/actions/setup-composer
      with:
        php-version: ${{ matrix.php-versions }}
        php-tools: composer, phpunit

    - name: Run coding standards check
      run: composer run cs:check

  eslint:
    runs-on: ubuntu-latest

    name: ESLint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: ./.github/actions/setup-node
        with:
          node-version: '16'

      - name: Run eslint
        run: npm run lint

  stylelint:
    runs-on: ubuntu-latest

    name: Stylelint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: ./.github/actions/setup-node
        with:
          node-version: '16'

      - name: Run stylelint
        run: npm run stylelint

