# SPDX-FileCopyrightText: 2024 Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
name: 'Lock Issues'

on: 
  schedule:
    - cron: '2 4 * * *'

concurrency: lock_issues

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v6
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: '31'
          exclude-issue-created-before: ''
          exclude-any-issue-labels: ''
          add-issue-labels: ''
          issue-comment: >
            This thread has been automatically locked since there has not been
            any recent activity after it was closed. Please open a new issue for
            related bugs.
          issue-lock-reason: 'resolved'
          process-only: 'issues'
