# SPDX-FileCopyrightText: 2020 Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
name: PHPUnit

on:
  pull_request:
  push:
    branches:
      - master
      - next
      - stable*

env:
  APP_NAME: polls
  SERVER_PATH: server
  DB_USER: root
  DB_PASSWORD: rootpassword
  DB_NAME: nextcloud

jobs:
  sqlite:
    runs-on: ubuntu-latest

    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: ['8.0']
        server-versions: ['stable27', 'stable30']

    name: SQLite

    steps:
      - uses: actions/checkout@v4
        with:
          path: src

      - name: Setup server
        uses: ./src/.github/actions/setup-server
        with:
          server-version: ${{ matrix.server-versions }}
          php-version: ${{ matrix.php-versions }}
          server-path: ${{ env.SERVER_PATH }}
          db-engine: sqlite

      - name: PHPUnit
        working-directory: ${{ env.SERVER_PATH }}/apps/${{ env.APP_NAME }}
        run: composer run phpunit:unit

      - name: PHPUnit integration
        working-directory: ${{ env.SERVER_PATH }}/apps/${{ env.APP_NAME }}
        run: composer run phpunit:integration

  mysql:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.0']
        server-versions: ['stable28']

    name: MySQL

    services:
      mysql:
        image: mysql:8.0
        # map port fix to 4444 for mysql
        ports:
          - 4444:3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
        options: --health-cmd="mysqladmin ping" --health-interval 5s --health-timeout 2s --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          path: src

      - name: Setup server
        uses: ./src/.github/actions/setup-server
        with:
          server-version: ${{ matrix.server-versions }}
          php-version: ${{ matrix.php-versions }}
          server-path: ${{ env.SERVER_PATH }}
          db-engine: 'mysql'

      - name: PHPUnit
        working-directory: ${{ env.SERVER_PATH }}/apps/${{ env.APP_NAME }}
        run: composer run phpunit:unit

      - name: PHPUnit integration
        working-directory: ${{ env.SERVER_PATH }}/apps/${{ env.APP_NAME }}
        run: composer run phpunit:integration

  pgsql:
    runs-on: ubuntu-latest
    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: ['8.0']
        server-versions: ['stable30']

    name: PostgreSQL

    services:
      postgres:
        image: postgres:14.5-bullseye
        # map port fix to 4445 for pgsql
        ports:
          - 4445:5432/tcp
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_NAME }}
        options: --health-cmd pg_isready --health-interval 5s --health-timeout 2s --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          path: src
      - name: Prepare server
        uses: ./src/.github/actions/setup-server
        with:
          server-version: ${{ matrix.server-versions }}
          php-version: ${{ matrix.php-versions }}
          server-path: ${{ env.SERVER_PATH }}
          db-engine: 'pgsql'

      - name: PHPUnit
        working-directory: ${{ env.SERVER_PATH }}/apps/${{ env.APP_NAME }}
        run: composer run phpunit:unit

      - name: PHPUnit integration
        working-directory: ${{ env.SERVER_PATH }}/apps/${{ env.APP_NAME }}
        run: composer run phpunit:integration
