name: PHPUnit

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

env:
  APP_NAME: polls
  SERVER_PATH: server
  DB_USER: root
  DB_PASSWORD: rootpassword
  DB_NAME: nextcloud
  MYSQL_PORT: 4444
  PGSQL_PORT: 5432

jobs:
  sqlite:
    runs-on: ubuntu-latest

    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: ['8.0']
        server-versions: ['stable25']

    name: SQLite

    steps:
      - uses: actions/checkout@v3
        with:
          path: src

      - name: Setup server
        uses: ./src/.github/actions/setup-server
        with:
          server-version: ${{ matrix.server-versions }}
          php-version: ${{ matrix.php-versions }}
          php-tools: phpunit:9
          server-path: ${{ env.SERVER_PATH }}
          db-engine: sqlite

      - name: PHPUnit
        working-directory: ${{ env.SERVER_PATH }}/apps/${{ env.APP_NAME }}
        run: phpunit -c tests/phpunit.xml

      - name: PHPUnit integration
        working-directory: ${{ env.SERVER_PATH }}/apps/${{ env.APP_NAME }}
        run: phpunit -c tests/phpunit.integration.xml

  mysql:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1']
        server-versions: ['stable26']

    name: MySQL

    services:
      mysql:
        image: mysql:8.0
        ports:
          -  4444:3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
        options: --health-cmd="mysqladmin ping" --health-interval 5s --health-timeout 2s --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          path: src

      - name: Setup server
        uses: ./src/.github/actions/setup-server
        with:
          server-version: ${{ matrix.server-versions }}
          php-version: ${{ matrix.php-versions }}
          php-tools: phpunit:9
          server-path: ${{ env.SERVER_PATH }}
          db-engine: 'mysql'
          mysql-port: ${{ env.MYSQL_PORT }}

      - name: PHPUnit
        working-directory: ${{ env.SERVER_PATH }}/apps/${{ env.APP_NAME }}
        run: phpunit -c tests/phpunit.xml

      - name: PHPUnit integration
        working-directory: ${{ env.SERVER_PATH }}/apps/${{ env.APP_NAME }}
        run: phpunit -c tests/phpunit.integration.xml

  pgsql:
    runs-on: ubuntu-latest
    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: ['8.2']
        server-versions: ['master']

    name: PostgreSQL

    services:
      postgres:
        image: postgres:14.5-bullseye
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_PORT: ${{ env.PGSQL_PORT }}
        options: --health-cmd pg_isready --health-interval 5s --health-timeout 2s --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          path: src
      - name: Prepare server
        uses: ./src/.github/actions/setup-server
        with:
          server-version: ${{ matrix.server-versions }}
          php-version: ${{ matrix.php-versions }}
          php-tools: phpunit:9
          server-path: ${{ env.SERVER_PATH }}
          db-engine: 'pgsql'
          pgsql-port: ${{ env.PGSQL_PORT }}

      - name: PHPUnit
        working-directory: ${{ env.SERVER_PATH }}/apps/${{ env.APP_NAME }}
        run: phpunit -c tests/phpunit.xml

      - name: PHPUnit integration
        working-directory: ${{ env.SERVER_PATH }}/apps/${{ env.APP_NAME }}
        run: phpunit -c tests/phpunit.integration.xml
