# SPDX-FileCopyrightText: 2021 Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
name: Static analysis

on:
  pull_request:
  push:
    branches:
      - master-*
      - next
      - stable*

jobs:
  psalm-master:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ocp-version: ['stable28', 'master']
        php-versions: ['8.1', '8.2', '8.3']

    name: Psalm

    steps:
      - uses: actions/checkout@v5

      - name: Setup composer and PHP
        uses: ./.github/actions/setup-composer
        with:
          php-version: ${{ matrix.php-versions }}
          php-tools: composer

      - name: Install Nextcloud API
        run: composer require --dev -W nextcloud/ocp:dev-${{ matrix.ocp-version }}

      - name: Install symfony/console
        run: composer require -W symfony/console

      - name: Run coding standards check
        run: composer run psalm
